version: "3.7"
services:
  auth-api:
    image: registry.digitalocean.com/magnus-images/other:auth-api-0.1.2
    env_file: '.env'
    container_name: auth-api
    networks:
      - social-app
    restart: unless-stopped

networks:
  social-app:
    external: true
