server:
  port: ${PORT}
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
app:
  api-key: ${API_KEY}
  upload-dir: ./media
  media-path: /media/**
  media-mapping: ${MEDIA_MAPPING}
  jwt-secret: ${JWT_SECRET}
  allowed-origins: ${ALLOWED_ORIGINS}