server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:db/master.xml
  output:
    ansi:
      enabled: ALWAYS
application:
  api:
    url: ${API_URL}
    allowed-origins: ${ALLOWED_ORIGINS}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    from: ${FROM_EMAIL}
    password: ${FROM_PASSWORD}
  jwt:
    secret-key: ${SECRET_KEY}
